import { z } from "zod";

export const isDate = (value: string): boolean => {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  const date = new Date(`${value}T00:00:00Z`);
  return Number.isFinite(date.getTime()) && date.toISOString().slice(0, 10) === value;
};

const date = z.string().refine(isDate, "Use a valid YYYY-MM-DD date");
const id = z.number().int().positive();
export const ganttDataSchema = z.object({
  project_ids: z.union([z.literal("all_accessible"), z.array(id).min(1).max(50)])
    .default("all_accessible"),
  user_id: z.union([z.literal("me"), id]).default("me"),
  user_scope: z.enum(["author", "assignee", "author_or_assignee"]).default("author"),
  from: date.describe("First schedule date, inclusive; maximum range is 366 days"),
  to: date.describe("Last schedule date, inclusive"),
  timezone: z.string().default("Asia/Jakarta")
    .refine(value => {
      try { new Intl.DateTimeFormat("en", { timeZone: value }); return true; }
      catch { return false; }
    }, "Use an IANA timezone"),
  working_days: z.array(z.enum(["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]))
    .min(1).max(7).default(["MON", "TUE", "WED", "THU", "FRI"]),
  excluded_dates: z.array(date).max(366).default([]),
  max_pages: z.number().int().min(1).max(200).default(100)
    .describe("Total issue page budget; reaching it reports an incomplete scan"),
});

export const ganttDetailSchema = z.object({
  scan_id: z.string().uuid().describe("Snapshot from getGanttData; expires after 10 minutes"),
  dates: z.array(date).min(1).max(31),
  include_nearby_issues: z.boolean().default(true),
  include_unscheduled: z.boolean().default(true),
  include_description: z.boolean().default(false),
  include_relations: z.boolean().default(false),
  include_journals: z.boolean().default(false),
  offset: z.number().int().nonnegative().default(0),
  limit: z.number().int().min(1).max(100).default(50),
});

export const dependencyTypes = ["precedes", "follows", "blocks", "blocked"] as const;
const scheduleDate = date.nullable().optional();
export const applyScheduleSchema = z.object({
  changes: z.array(z.object({
    issue_id: id,
    start_date: scheduleDate.describe("New start date; null clears it; omit to keep the current value"),
    due_date: scheduleDate.describe("New due date; null clears it; omit to keep the current value"),
  }).refine(change => change.start_date !== undefined || change.due_date !== undefined,
    "Provide start_date and/or due_date")).max(50).default([]),
  dependencies: z.array(z.object({
    issue_id: id, issue_to_id: id,
    relation_type: z.enum(dependencyTypes).default("precedes")
      .describe("issue_id <relation_type> issue_to_id, e.g. 1 precedes 2"),
    delay: z.number().int().min(0).max(365).optional().describe("Delay in days; precedes/follows only"),
  }).refine(dependency => dependency.issue_id !== dependency.issue_to_id, "An issue cannot depend on itself")
    .refine(dependency => dependency.delay === undefined || ["precedes", "follows"].includes(dependency.relation_type),
      "delay is only valid for precedes/follows")).max(50).default([]),
  notes: z.string().max(2000).optional().describe("Journal note added to every issue whose dates change"),
  dry_run: z.boolean().default(true).describe("Default true: report planned changes without writing"),
});

export const ganttCapabilitiesSchema = z.object({
  project_id: id.optional().describe("Also check this project's Gantt module and project-level export routes"),
});

export const exportFormats = ["pdf", "png", "csv", "mermaid"] as const;
export const exportGanttSchema = z.object({
  format: z.enum(exportFormats),
  source: z.enum(["auto", "plugin", "mcp"]).default("auto")
    .describe("auto: pdf/png from Redmine's Gantt export, csv/mermaid generated by this MCP server"),
  from: date.describe("First date of the chart, inclusive"),
  to: date.describe("Last date of the chart, inclusive; maximum range is 366 days"),
  project_id: id.optional().describe("Limit to one project (Redmine applies its subproject setting)"),
  issue_ids: z.array(id).min(1).max(100).optional().describe("MCP-generated charts only: chart exactly these issues"),
  include_closed: z.boolean().default(true),
  include_relations: z.boolean().default(true).describe("MCP-generated charts only: list dependencies"),
  max_pages: z.number().int().min(1).max(20).default(5).describe("MCP-generated charts only: issue page budget"),
});

export type GanttDataArgs = z.infer<typeof ganttDataSchema>;
export type GanttDetailArgs = z.infer<typeof ganttDetailSchema>;
export type ApplyScheduleArgs = z.infer<typeof applyScheduleSchema>;
export type ExportGanttArgs = z.infer<typeof exportGanttSchema>;
